# Uncomment the next line to define a global platform for your project
ENV['SWIFT_VERSION'] = '5'  # or the desired Swift version
platform :ios, '15.4'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :dynamic
    pod 'composeApp', :path => '../composeApp'
    pod 'StoreKit', '1.1'
    pod 'FirebaseCore', '11.4.2'
    pod 'GoogleSignIn', '8.0'
  # Pods for iosApp

end
