services:
 server:
    build: ./idioms-quial
    volumes:
      - shared-volume:/usr/src/app
    ports:
      - "8081:8081"

 scraper:
    build: ./idioms-quial/src/main/kotlin/com/backend/quial/python
    volumes:
      - shared-volume:/usr/src/app
    ports:
      - "8080:8080"

 onboarding:
   build: ./onboarding-quial
   volumes:
     - onboarding-quial:/usr/src/app
   ports:
     - "8082:8082"

volumes:
  shared-volume:
  onboarding-quial:
  
