services:
 idiom-quial-microservice:
    build: .
    volumes:
      - shared-volume:/usr/src/app
    ports:
      - "5001:5001"

 idiom-scraper-microservice:
  build: ./src/main/kotlin/com/backend/quial/python
  volumes:
    - shared-volume:/usr/src/app
  ports:
    - "5002:5002"

volumes:
  shared-volume:
