services:
 idiom-quial-microservice:
    build: .
    volumes:
      - shared-volume:/usr/src/app
    ports:
      - "8080:8080"

 idiom-scraper-microservice:
  build: ./src/main/kotlin/com/backend/quial/python
  volumes:
    - shared-volume:/usr/src/app
  ports:
    - "8081:8081"

volumes:
  shared-volume:
